### ISSUE TITLE
登出錯誤

### ISSUE THREAD

**Issue by FOBshippingpoint** [aga3134/CommuTag#47]
## BUG描述

點選登出按鈕時顯示錯誤 traceback 無法登出。

## 重現步驟

1. 登入帳號
2. 進入`https://commutag.agawork.tw/account`
3. 點選登出
![圖片](https://user-images.githubusercontent.com/60565355/211722696-7545994e-1474-4120-97fb-e2b6ac882b03.png)

## 預期行為

成功登出

## 瀏覽器

- Firefox 108.0.2（64 位元）
- Google Chrome 108.0.5359.125 (正式版本) (64 位元)

## 錯誤訊息

```
Error: req#logout requires a callback function
    at IncomingMessage.req.logout.req.logOut (/CommuTag/node_modules/passport/lib/http/request.js:65:44)
    at /CommuTag/app/route/authRoute.js:56:9
    at Layer.handle [as handle_request] (/CommuTag/node_modules/express/lib/router/layer.js:95:5)
    at next (/CommuTag/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/CommuTag/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/CommuTag/node_modules/express/lib/router/layer.js:95:5)
    at /CommuTag/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/CommuTag/node_modules/express/lib/router/index.js:341:12)
    at next (/CommuTag/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/CommuTag/node_modules/express/lib/router/index.js:174:3)
    at router (/CommuTag/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/CommuTag/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/CommuTag/node_modules/express/lib/router/index.js:323:13)
    at /CommuTag/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/CommuTag/node_modules/express/lib/router/index.js:341:12)
    at next (/CommuTag/node_modules/express/lib/router/index.js:275:10)
```

根據以上訊息，我想是這邊沒有提供callback function而導致的錯誤：
https://github.com/aga3134/CommuTag/blob/c6ee29319e4c709da96faf440c8a2023aa7127df/app/route/authRoute.js#L55-L58

依照passportjs的[文件](https://www.passportjs.org/concepts/authentication/logout/)，似乎應該改為：
```js
router.get('/logout', function(req, res) {
    req.logout(function(err) {
      if (err) { return console.log(err); }
      res.redirect('/');
    });
});
```

**Comment by aga3134** [comment]
是的，新版的passport需要用callback的方式做logout。
程式已修正，謝謝。
